server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  ssl:
    key-store: /tmp/keystore/IBMKeyStore.jks
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: JKS
    key-store-provider: SUN
    key-alias: ${SSL_KEY_ALIAS}
    trust-store: /tmp/keystore/IBMTrustStore.jks
    trust-store-password: ${TRUSTSTORE_PASSWORD}
    trust-store-type: JKS
    trust-store-provider: SUN
    enabled: ${SSL_ENABLED:false}
  max-http-request-header-size: ${MAX_HTTP_HEADER_SIZE:40KB}

spring:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@
  banner:
    location: classpath:banner.txt
  logging:
    pattern:
      console: "%highlight{ %d{ISO8601} %-5level}{ERROR=red, WARN=yellow, TRACE=blue, INFO=blue, DEBUG=green} %style{[%threadName-%threadId]}{bright,blue} %style{%class{2}:}{bright,yellow} %msg%n%style{%throwable}{bright,red}"
    level:
      root: ${LOGGING_ROOT_LEVEL:INFO}
      com:
        ibm: ${LOGGING_PACKAGE_LEVEL:INFO} 

management:
  endpoints:
    web:
      base-path: /api/v1
      exposure:
        include: health

app:
  web-security:
    cors-allowed-origins: ${CORS_ALLOWED_ORIGINS}
  ibm-cloud:
      api-key: ${IBM_CLOUD_API_KEY}
      secrets-manager-service-url: ${IBM_CLOUD_SECRETS_MANAGER_SERVICE_URL}
      key-store-secret-id: ${KEY_STORE_SECRET_ID}
      trust-store-secret-id: ${TRUST_STORE_SECRET_ID}
